=head1 ASYNC Perl 5 vs Perl 6 Grudge Match

Here are some examples for DC.pm wherein we will attempt to compare and 
contrast the various asynchronous APIs in Perl 5 and Perl 6.

The intent is to keep the examples as simple and easy to understand for 
the purposes of discussion and ease of translation.

=head1 EXAMPLES

=head2 anyevent-finger.pl

Demonstrates low-level non-blocking sockets in a single thread using the 
archaic, but simple "finger" protocol.

=head2 anyevent-fingerd.pl

Demonstrates higher level non-blocking finger server.  Mainly just 
designed to test L</anyevent-finger.pl>

=head2 mojo-mirror.pl

Demonstrates high level HTTP non-blocking in a single thread using 
Mojolicious.

=cut
